# config/simulation_config.yml

initial_state:
  x: 0.0
  y: 0.0
  theta: 0.0

mpc:
  horizon: 20   #Originallyset at 20  50
  time_step: 0.1
  state_weights: [10.0, 10.0, 1.0]
  control_weights: [0.1, 0.1]
  terminal_weight: 50.0
  state_weight: 10.0   
  control_weight: 0.1  
  obstacle_weight: 10.0

control_limits:
  v_min: -2.0
  v_max: 2.0
  omega_min: -1.57
  omega_max: 1.57

simulation:
  max_steps:  1000
  num_points: 300
  completion_threshold: 0.01
  min_iterations: 50

visualization:
  update_interval: 5

debug:
  enabled: true  
  log_level: DEBUG

convergence:
  position_tolerance: 0.001                     # meters
  orientation_tolerance: 0.01                   # radians
  control_tolerance: 0.001                      # control units
  window_size: 5                                # number of samples for convergence check
  min_convergence_steps: 20
  analysis:
    error_threshold: 0.05
    settling_window: 10
    convergence_rate_threshold: 0.1

obstacles:
  static:
    - position: [5.0, 1.0]
      radius: 0.5
    - position: [10.0, -1.0]
      radius: 0.5
  dynamic:
    - type: "circular"
      center_x: 7.0
      center_y: 0.0
      radius: 0.3
      angular_velocity: 0.5
      circle_radius: 1.0
    - type: "linear"
      start_x: 3.0
      start_y: -1.0
      velocity_x: 0.2
      velocity_y: 0.1
      radius: 0.4
  safety_distance: 1.0                  # Minimum distance to keep from obstacles
  weight: 10.0                          # Weight for obstacle avoidance in cost function